name: SignShop
main: org.wargamer2010.signshop.SignShop
version: 2.11.2
dev-url: http://dev.bukkit.org/server-mods/signshop
authors: [Wargamer2010, Devinish, lieuwe_berg]
softdepend: [Vault, Multiverse-Core, ShowCaseStandalone, Deadbolt, Notifications, dynmap, Towny, WhatIsIt]
commands:
  signshop:
    description: Admin commands for SignShop
    usage: /signshop [reload|stats|version|about|help|sign|tutorial]
